# Generated by Django 2.2.7 on 2019-12-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
